apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
spec:
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
      - name: order-service-app
        image: udaydasari369369/pm_orderservice
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
        env:
         - name: EUREKA_SERVER_ADDRESS
           valueFrom:
            configMapKeyRef:
              key: eureka-service-address
              name: eureka-config-map
         - name: CONFIG_SERVER_URL
           valueFrom:
            configMapKeyRef:
              key: config-url
              name: config-config-map
         - name: DB_HOST
           valueFrom:
              configMapKeyRef:
                key: hostname
                name: mysql-cm
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service-app
  ports:
  - port: 80
    targetPort: 8082
