server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: Sai369uy@
    driverClassname: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296

#  eureka:
#    client:
#      fetch-register-true: true
#      register-with-eureka: true
#      service-url:
#        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}



